apiVersion: v1
kind: Service
metadata:
  name: cine-platform
  namespace: cine
spec:
  type: NodePort
  selector:
    app: cine-platform
  ports:
    - port: 9443
      targetPort: 9443
      nodePort: 30443
