apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cine-platform-ingress
  namespace: cine
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - cine.nbes.blog
      secretName: cine-platform-tls
  rules:
    - host: cine.nbes.blog
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cine-platform
                port:
                  number: 9443